AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Test written with SpringBoot with the aws-serverless-java-container
  library
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Outputs:
  LambdaTest:
    Description: URL for application
    Export:
      Name: LambdaTest
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
Resources:
  LambdaTestFunction:
    Properties:
      CodeUri: s3://leon.lambda.test/cfaaf468fde054505385102980b4f87a
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: uk.gov.ons.lambdatest.LambdaTest::handleRequest
      MemorySize: 2048
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
