AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Test written with SpringBoot with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  LambdaTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: uk.gov.ons.lambdatest.LambdaTest::handleRequest
      Runtime: java8
      CodeUri: target/lambdatest-0.0.1-SNAPSHOT-lambda-package.zip
      MemorySize: 2048
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  LambdaTest:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: LambdaTest